server.port=8080

app.session.ttl=PT30M
app.cache.user-profile.ttl=PT5M

app.storage=riak
app.riak.nodes=${RIAK_NODES:1.riak.dc.lysmux.dev:8087,2.riak.dc.lysmux.dev:8087,3.riak.dc.lysmux.dev:8087}
app.riak.timeout=PT2S
